### ISSUE TITLE
MVPリリースのレビュー依頼

### ISSUE THREAD

**Issue by takuma-kamimura** [takuma-kamimura/NeCommunity#78]

**Comment by takuma-kamimura** [comment]
ご返信ありがとうございます。
まずはレビュー依頼を行なったもののコメントを記載せず、失礼いたしました。

### 実装途中に行なった設計段階からの変更箇所
----------------------------------
以下、実装を行なっている最中で当初の予定と変更した点でございます。

* ご質問のLINE通知機能ですが開発の途中で機能として加えるべきか再度検討したいと考え、今回は実装を行いませんでした。
なので今回「高度な機能」で実装を行なったのは「オートコンプリート機能」となります。

* コメントの編集機能についてですが、コメントに関しての編集機能は必要か否か再検討したいと考え、まずは投稿機能・投稿削除機能のみ実装を行わせていただきました。

* ユーザビリティを考慮して最初に提出させていただいた画面遷移図の内容から導線を少し変更いたしました。

* ユーザーのプロフィール写真、猫のプロフィール写真解除機能を実装いたしました。

* 退会機能を実装いたしました。

### ご要望のスクリーンショット等について
-------------------------------------

以下ご要望のあったスクリーンショットとなります。ご確認をよろしくお願いします。

### 健康状態記録機能(体調や体重)・記録削除機能・記録編集機能
* ユーザーの猫一覧
[![Image from Gyazo](https://i.gyazo.com/649936393f822e433b081ea3c161d54f.png)](https://gyazo.com/649936393f822e433b081ea3c161d54f)
* ユーザーの猫別健康記録一覧
[![Image from Gyazo](https://i.gyazo.com/c56bbaee0312290ccf35627a0889c2f7.png)](https://gyazo.com/c56bbaee0312290ccf35627a0889c2f7)
* 健康記録新規作成画面
 [![Image from Gyazo](https://i.gyazo.com/983c120a15fa84e0da0bb7b4dbc2fabe.png)](https://gyazo.com/983c120a15fa84e0da0bb7b4dbc2fabe)
* 健康記録詳細画面
 [![Image from Gyazo](https://i.gyazo.com/a030165aa84a1be7f7e6dd1d2c01a32b.png)](https://gyazo.com/a030165aa84a1be7f7e6dd1d2c01a32b)
* 健康記録編集画面
[![Image from Gyazo](https://i.gyazo.com/f98f672a80fa7616f8065ed6de955ecd.png)](https://gyazo.com/f98f672a80fa7616f8065ed6de955ecd)
* 健康記録削除機能
[![Image from Gyazo](https://i.gyazo.com/b03e9785986d453d063df4bfcbb217f8.png)](https://gyazo.com/b03e9785986d453d063df4bfcbb217f8)

### 管理者機能

* ご評価用に管理者権限ユーザーを一つお作りいたしました。良ければご評価用にお使いください。
ご確認をよろしくお願いします。
ログインメールアドレス：test@email.jp
ログインパスワード：test

* ログインページ
[![Image from Gyazo](https://i.gyazo.com/e821ceaee8eed27974db4c3c0dd85ae5.png)](https://gyazo.com/e821ceaee8eed27974db4c3c0dd85ae5)
 * 投稿一覧
 [![Image from Gyazo](https://i.gyazo.com/ae7dca9effa89c1109fa991619c093f5.png)](https://gyazo.com/ae7dca9effa89c1109fa991619c093f5)
* 投稿詳細
[![Image from Gyazo](https://i.gyazo.com/ed8307b1c6dcce49e65c8130569175cf.jpg)](https://gyazo.com/ed8307b1c6dcce49e65c8130569175cf)
[![Image from Gyazo](https://i.gyazo.com/d277d6c50c24eb04fab7c3956d3881cd.jpg)](https://gyazo.com/d277d6c50c24eb04fab7c3956d3881cd)
* 投稿編集
[![Image from Gyazo](https://i.gyazo.com/ba60af61a2d7d522545ab5aeaa40d5f9.png)](https://gyazo.com/ba60af61a2d7d522545ab5aeaa40d5f9)
* 投稿削除機能
[![Image from Gyazo](https://i.gyazo.com/9d4504cf86ca7e8f754498b65913a6c9.png)](https://gyazo.com/9d4504cf86ca7e8f754498b65913a6c9)
* ユーザー一覧
[![Image from Gyazo](https://i.gyazo.com/16b8203835d8e4be0f2a31734d02dbd3.png)](https://gyazo.com/16b8203835d8e4be0f2a31734d02dbd3)
* ユーザー詳細
[![Image from Gyazo](https://i.gyazo.com/be0e6a2eb534cc09065648423b568cc2.png)](https://gyazo.com/be0e6a2eb534cc09065648423b568cc2)
* ユーザー編集
[![Image from Gyazo](https://i.gyazo.com/99274bb9c667d86109689f9b2fe8974c.png)](https://gyazo.com/99274bb9c667d86109689f9b2fe8974c)
[![Image from Gyazo](https://i.gyazo.com/45ad663f1fe12bf3333052ef6134aa7c.jpg)](https://gyazo.com/45ad663f1fe12bf3333052ef6134aa7c)
* ユーザー削除機能
[![Image from Gyazo](https://i.gyazo.com/fa476be16223a89cbd02fff4e5c1dffd.png)](https://gyazo.com/fa476be16223a89cbd02fff4e5c1dffd)
* コメント一覧
[![Image from Gyazo](https://i.gyazo.com/5c85e5e21da6291fc7ab2317ace53488.png)](https://gyazo.com/5c85e5e21da6291fc7ab2317ace53488)
* コメント詳細
[![Image from Gyazo](https://i.gyazo.com/b768b29fdadb31b29bde2ad78d448d73.png)](https://gyazo.com/b768b29fdadb31b29bde2ad78d448d73)
* コメント編集
[![Image from Gyazo](https://i.gyazo.com/97c5149f49127f5c798a489e5373f20c.png)](https://gyazo.com/97c5149f49127f5c798a489e5373f20c)
* コメント削除
[![Image from Gyazo](https://i.gyazo.com/dd2a54fcfd960a95d602f2f848847304.png)](https://gyazo.com/dd2a54fcfd960a95d602f2f848847304)
* 猫一覧
[![Image from Gyazo](https://i.gyazo.com/0d72b7b1bf1a37885853d1c566cb4f4e.png)](https://gyazo.com/0d72b7b1bf1a37885853d1c566cb4f4e)
* 猫詳細
[![Image from Gyazo](https://i.gyazo.com/5a5ccdff4e6d6395b6471e682ba7dd2f.png)](https://gyazo.com/5a5ccdff4e6d6395b6471e682ba7dd2f)
[![Image from Gyazo](https://i.gyazo.com/d47af145ff3b1ca68a7b977dc35ca3e7.png)](https://gyazo.com/d47af145ff3b1ca68a7b977dc35ca3e7)
* 猫編集
[![Image from Gyazo](https://i.gyazo.com/d750e5ff52aef517f653af440e1c470d.png)](https://gyazo.com/d750e5ff52aef517f653af440e1c470d)
[![Image from Gyazo](https://i.gyazo.com/f566ed9a0a1e3949b7ce6a4394103ac7.png)](https://gyazo.com/f566ed9a0a1e3949b7ce6a4394103ac7)
* 猫削除機能
[![Image from Gyazo](https://i.gyazo.com/dfc750fb57ba896f2777acfc9366036e.png)](https://gyazo.com/dfc750fb57ba896f2777acfc9366036e)
* 健康管理一覧
[![Image from Gyazo](https://i.gyazo.com/23001fd3a73f72c7816dcb20f311897b.png)](https://gyazo.com/23001fd3a73f72c7816dcb20f311897b)
* 猫別健康管理一覧
[![Image from Gyazo](https://i.gyazo.com/77b36d211cff7a014b719bf1777b4f05.png)](https://gyazo.com/77b36d211cff7a014b719bf1777b4f05)
*. 健康管理記録詳細
[![Image from Gyazo](https://i.gyazo.com/b71c3d6963c341076aa31ef9cc5834b7.png)](https://gyazo.com/b71c3d6963c341076aa31ef9cc5834b7)
* 健康管理記録編集
[![Image from Gyazo](https://i.gyazo.com/92c95f5e0274aa32f63b3f20849161b7.png)](https://gyazo.com/92c95f5e0274aa32f63b3f20849161b7)
* 健康記録削除
[![Image from Gyazo](https://i.gyazo.com/735dadac96b8308e90df209fbaee26bf.png)](https://gyazo.com/735dadac96b8308e90df209fbaee26bf)
* タグ一覧
[![Image from Gyazo](https://i.gyazo.com/f230669821ae8be0ce562145452e6fd7.png)](https://gyazo.com/f230669821ae8be0ce562145452e6fd7)
* タグ詳細
[![Image from Gyazo](https://i.gyazo.com/042801ee25cd581941d1644b426b64f8.png)](https://gyazo.com/042801ee25cd581941d1644b426b64f8)
* タグ編集画面
[![Image from Gyazo](https://i.gyazo.com/972b6c38d77c4b2ae438152b826a43c5.png)](https://gyazo.com/972b6c38d77c4b2ae438152b826a43c5)
* タグ削除
[![Image from Gyazo](https://i.gyazo.com/235f91245e2f003cd23edbe8a1cf7224.png)](https://gyazo.com/235f91245e2f003cd23edbe8a1cf7224)
-------------------------------------

* 以下、再度整理した実装内容となっております。

- [x]  会員登録・ログイン・退会
- [x] トップページ
- [x] 投稿一覧表示・猫種、タグ、カテゴリ、ブックマーク、いいねで絞った投稿検索
- [x] コンテンツ投稿機能（猫種選択、カテゴリやタグを生成か選択できる機能）、投稿編集機能
- [x] 投稿詳細
- [x] ユーザープロフィールページ登録、編集
- [x] ユーザー詳細
- [x] ユーザーの飼っている猫登録機能(飼っていなければパス)・削除機能・編集機能
- [x] ユーザーの飼っている猫一覧
- [x] ユーザーの飼っている猫詳細
- [x] いいね機能・いいね削除機能
- [x] ブックマーク機能・ブックマーク削除機能
- [x] メールアドレス・パスワード変更機能
- [x] オートコンプリートで投稿一覧検索時の候補を出して入力の手間を省く機能
- [x] コメント機能・コメント削除機能
- [x] コメント詳細(投稿詳細ページの下部に設置)
- [x] 自分と同じ猫種を飼っている投稿のみ絞り込んで表示する機能
- [x] 自分の飼っている猫種と同じ猫種別に投稿内容を絞り込んで表示する機能
- [x] 管理者機能(user,cat,post,comment,health_record,tagの詳細・編集・削除機能)
- [x] 健康状態記録機能(体調や体重)・記録削除機能・記録編集機能

以上、ご確認をよろしくお願いします。

**Comment by kenchasonakai** [comment]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. フレームワークの特性を活かし冗長なコードを書いていないか
3. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
- きちんと実装されていそうな感じでした

## フレームワークの特性を活かし冗長なコードを書いていないか
- 全体的に綺麗に書けていました

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
気になった箇所を挙げたのでご確認ください。
- Topページの投稿一覧ページへのリンクが背景色と同化してしまっているのでサイズを大きくして文字がみやすくする工夫をすると良いと思います
- 配色や要素など他のサイトを参考にブラッシュアップすると良いかなと思います
  - https://partsdesign.net/
  - https://design-library.jp/ui/

**Comment by takuma-kamimura** [comment]
kenchasonakai様

ご評価いただきありがとうございます。

以下のご指摘事項について確認いたしました。
## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
-----------------------------------
* Topページの投稿一覧ページへのリンクが背景色と同化してしまっているのでサイズを大きくして文字がみやすくする工夫をすると良いと思います
→ アドバイス通り、投稿一覧ページのリンクの色とサイズを大きくして、おしゃれな字体があればそのような形で実装を行なってみようかと思います。
* 配色や要素など他のサイトを参考にブラッシュアップすると良いかなと思います
https://partsdesign.net/
https://design-library.jp/ui/
→ご教授いただき大変にありがとうございます。ぜひ、ご提示いただいたリンクを参考にして試行錯誤しながら更なるブラッシュアップを行なっていきます。

また今後ともよろしくお願いします。ありがとうございました。
